name: CD workflow

on:
  workflow_run:
    workflows: ["CI workflow"]  
    types: [completed]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para deploy (dev=checa, prod=publica)'
        required: true
        default: 'dev'
        type: choice
        options: [dev, prod]

permissions:
  contents: write

jobs:
  deploy_docs:
    if: >
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do commit aprovado (ou da ref atual no manual)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            mkdocs.yml

      - name: Instalar MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build docs (clean)
        run: mkdocs build --clean

   

      - name: Skip publish (manual: dev)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.environment == 'dev' }}
        run: echo "Ambiente dev: apenas build (sem publicar)"
