name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            tests/requirements.txt
            pyproject.toml
            setup.cfg

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project dependencies
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Install test dependencies
        if: hashFiles('tests/requirements.txt') != ''
        run: pip install -r tests/requirements.txt

      - name: Install package (editable)
        run: pip install -e .

      - name: Run tests
        run: python -m unittest discover -s tests -p "test*.py"
